#!/bin/sh

set -e
cd "$(dirname "$0")/.."

if [ "$#" -lt 2 ]; then
  echo "Usage: $0 @<username> <reason>"
  echo "e.g: $0 @spongebob for helping me with my krabby patty!"
  exit 1
fi

HOST=${HOST:-http://localhost:8080}
curl -s "$HOST/sparkles.json" -d "{\"body\":\"$*\"}"
