#!/bin/sh

set -e

if [ "$#" -lt 2 ]; then
  echo "Usage: $0 @<username> <reason>"
  echo "e.g: $0 @monalisa for helping me with my homework!"
  exit 1
fi

HOST=${HOST:-http://localhost:8080}
body="$(echo "$@" | sed 's/ /+/g')"
curl -i -s "$HOST/sparkles" -d "body=$body"
