name: CI
on:
  - push
  - pull_request_target
  - workflow_dispatch
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: ./script/test
